<?php

/*
 |--------------------------------------------------------------------------
 | DO NOT EDIT THIS FILE DIRECTLY.
 |--------------------------------------------------------------------------
 | This file reads from your .env configuration file and should not
 | be modified directly.
*/


return [
    /* <printer-name>=<ip_address:port> */
    'printers' => env("PRINT_SERVER",""),
    /*-1=<default name>;<location-id>=<printer name>;...*/
    'location_mapping' => env("LOCATION_MAPPING",""),
];