<?php

/*
 |--------------------------------------------------------------------------
 | Network label printer configuration (custom fork feature)
 |--------------------------------------------------------------------------
 |
 | Hybrid addition alongside Snipe-IT's native (PDF/DYMO) label engine: this
 | drives an external network print-server daemon over HTTP, auto-selecting a
 | printer by the item's location.
 |
 | Values come from the environment and are parsed into associative arrays:
 |
 |   PRINT_SERVER      "name1=http://10.0.0.5:9100;name2=http://10.0.0.6:9100"
 |                     -> ['name1' => 'http://10.0.0.5:9100', ...]
 |
 |   LOCATION_MAPPING  "-1=name1;5=name2;7=name2"
 |                     -> ['-1' => 'name1', '5' => 'name2', '7' => 'name2']
 |                     ('-1' is the fallback used when no location maps.)
 |
 | Do not edit this file directly; set the env vars instead.
*/

$parsePairs = function (string $raw): array {
    $pairs = [];

    foreach (array_filter(array_map('trim', explode(';', $raw))) as $pair) {
        if (! str_contains($pair, '=')) {
            continue;
        }

        [$key, $value] = explode('=', $pair, 2);
        $key = trim($key);
        $value = trim($value);

        if ($key !== '' && $value !== '') {
            $pairs[$key] = $value;
        }
    }

    return $pairs;
};

return [
    // Map of printer name => print-server base URL.
    'printers' => $parsePairs((string) env('PRINT_SERVER', '')),

    // Map of top-level location id => printer name ('-1' = default fallback).
    'location_mapping' => $parsePairs((string) env('LOCATION_MAPPING', '')),
];
