<?php

/*
 |--------------------------------------------------------------------------
 | Network label printer configuration (custom fork feature)
 |--------------------------------------------------------------------------
 |
 | Hybrid addition alongside Snipe-IT's native (PDF/DYMO) label engine: this
 | drives an external network print-server daemon over HTTP, selecting the
 | printer by the item's location.
 |
 | Both variables use the same syntax: semicolon-separated `key=value` pairs.
 |
 | 1. PRINT_SERVER declares the printers. `name=url`, where the name is yours to
 |    choose — it is only a label used by the UI and by LOCATION_MAPPING:
 |
 |      PRINT_SERVER="berlin=http://10.0.0.5:9100;munich=http://10.0.1.5:9100"
 |
 |    ...defines two printers, "berlin" and "munich".
 |
 | 2. LOCATION_MAPPING says which printer to use for which location.
 |    `location_id=printer_name` — the KEY is a Snipe-IT **location record id**
 |    (the number in the URL when you open that location: /locations/12), and the
 |    VALUE is one of the printer names declared above:
 |
 |      LOCATION_MAPPING="-1=berlin;3=berlin;12=munich"
 |
 |    ...reads as: "location #3 prints on berlin, location #12 prints on munich,
 |    and anything without a location prints on berlin."
 |
 | Two rules about the lookup:
 |
 |   - Only **top-level (root)** location ids are consulted. An asset in
 |     "Munich Office > Floor 2 > Room 5" is looked up under the id of
 |     "Munich Office", so you only map your sites, not every room.
 |   - The special key '-1' applies **only** to items that have no location at
 |     all. It is not a catch-all: an item whose root location is missing from
 |     the mapping prints nowhere and reports an error, so a Munich label can
 |     never silently come out in Berlin.
 |
 | Do not edit this file directly; set the env vars instead.
*/

$parsePairs = function (string $raw): array {
    $pairs = [];

    foreach (array_filter(array_map('trim', explode(';', $raw))) as $pair) {
        if (! str_contains($pair, '=')) {
            continue;
        }

        [$key, $value] = array_map('trim', explode('=', $pair, 2));

        if ($key !== '' && $value !== '') {
            $pairs[$key] = $value;
        }
    }

    return $pairs;
};

return [
    // Map of printer name => print-server base URL.
    'printers' => $parsePairs((string) env('PRINT_SERVER', '')),

    // Map of top-level location id => printer name ('-1' = items without a location).
    'location_mapping' => $parsePairs((string) env('LOCATION_MAPPING', '')),
];
